services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - db
    
  worker:
    build: .
    command: celery -A celery_app.celery worker --loglevel=info --concurrency=2
    env_file:
      - .env
    depends_on:
      - redis
      - db

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crewai
    ports:
      - "5432:5432"
 
